apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmlingua-demo-data
  namespace: cornelius-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-internal
