apiVersion: v1
kind: Service
metadata:
  name: llmlingua-demo-service
  namespace: cornelius-ns
  annotations:
    prometheus.io.scrape: "false"
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  selector:
    app: llmlingua-demo
